Ozon 23
go-park-mail-ru/2021_1_DuckLuck pull request #4
Opened 2021-03-01 18:40 UTC by Tullerpeton

Сделал:
1. `Session Model`
2. Управление сессиями через `session usecase`
3. `Delivery Session` нет поскольку в API доступа к сессии напрямую нет

2021-03-01 22:34 UTC, mortawe requested changes
уровень юзкейса размазан и выполняет работу хендлеров

с контекстами что то непонятное

ошибки желательно бы систематизировать и переиспользовать

2021-03-01 22:34 UTC, mortawe commented on internal/pkg/session/usecase/usecase.go
> +
Импорты либо делить на группы (стандартные модули гошки, модули проекта, остальные опенсурсные модули), либо слить в одну большую группу, а то тут это деление не имеет смысла

2021-03-01 22:34 UTC, mortawe commented on internal/pkg/session/usecase/usecase.go
> +func (h *UseCase) Check(r *http.Request) (*models.Session, error) {
Замечание: http - уровень хендлеров, юзкейс ничего не должен знает про реквест

2021-03-01 22:34 UTC, mortawe commented on internal/pkg/session/usecase/usecase.go
> +		return nil, errors.Wrap(err, "don't find cookie = session_id")
Рекомендация: Юзкейс вернет ошибку в хендлер. Как по такой ошибке понять, что возвращать клиенту -  401 - что не авторизован, или 400 - что плохой запрос?

2021-03-01 22:34 UTC, mortawe commented on internal/pkg/session/usecase/usecase.go
> +		return nil, errors.Wrap(err, "user unauthorized")
Рекомендация: В случае r.Cookie выше такой однозначный врап ошибки уместен - метод Cookie() возвращает либо nil, либо ErrNoCookie.
В общем случае репозиторий может вернуть ошибку по типу "не могу постучаться в базу".
Но не страшно, если это проигнорировать. 

Такие ошибки хорошо будет вынести в глобальные вар и переиспользовать - неавторизованный юзер много где встретится и не обязательно в таких случаях пробрасывать ошибку из базы. 

Если нужно прочитать содержание err с целью дебага - можно вывести ее значение в лог.

2021-03-01 22:34 UTC, mortawe commented on internal/pkg/session/usecase/usecase.go
> +	ctx = context.WithValue(ctx, models.SessionContextKey, sess)
Замечание: Какая цель у этого? Добавить Key - Value в контекст? 

Это сделало переменную ctx наследником r.Context() и никак не повлияло на родителя

2021-03-01 22:34 UTC, mortawe commented on internal/pkg/session/usecase/usecase.go
> +	cookie := &http.Cookie{
Замечание: тоже хендлеровская работа

2021-03-02 18:20 UTC, Tullerpeton commented
Исправил:
1. Создал константные ошибки, которые можно переиспользовать
2. Поправил логику `session_usecase`
3. Сделал middleware `Auth`, которая проверяет состояние сессии юзера. Если неудача - то выводится сообщение, что юзер не авторизован. Иначе сессия добавляется в контекс и в будущем потом можно будет идти в другую БД и брать юзера по `session.ID`

2021-03-02 18:33 UTC, mortawe approved these changes
Думаю, переопределенные ошибки юзкейса содержат внутри себя лишнюю информацию в виде http статуса, но  считаю это допустимым.

Все супер, апрув

2021-03-02 18:37 UTC, merged